version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: homecloudauthsevice
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: homecloud
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth_service:
    build:
      context: .
      dockerfile: ./auth_service/Dockerfile
    volumes:
      - ../server/database_service:/server/database_service
      - ../server/.env:/server/.env
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://homecloudauthsevice:123@db:5432/homecloud

volumes:
  db_data:
