name: Check docker-compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PostgreSQL
        run: |
          sudo apt update
          sudo apt install -y postgresql postgresql-contrib

      - name: Start PostgreSQL service
        run: |
          sudo service postgresql start
          sleep 5

      - name: Set up PostgreSQL user and database
        env:
          PGPASSWORD: postgres
        run: |
          sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"
          sudo -u postgres psql -c "CREATE DATABASE homecloud;"
          sudo -u postgres psql -d homecloud -c "CREATE USER homecloudauthsevice WITH ENCRYPTED PASSWORD '123';"
          sudo -u postgres psql -d homecloud -c "GRANT ALL PRIVILEGES ON DATABASE homecloud TO homecloudauthsevice;"

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Stop PostgreSQL service
        run: |
          sudo service postgresql stop

      - name: Start Docker Compose
        run: |
          cd server
          docker-compose -f docker-compose.yml up -d --build > log/docker.log 2>&1

      - name: Upload log artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-log
          path: server/log/docker.log
