name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: homecloudauthsevice
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: homecloud
        ports:
          - 5432:5432
        volumes:
          - db_data:/var/lib/postgresql/data

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r server/auth_service/requirements.txt

    - name: Run auth_service.py
      run: |
        . venv/bin/activate
        python3 /server/auth_service/auth_service.py # Запуск сервиса в фоновом режиме
        sleep 10 # Даем время на запуск

    - name: Run tests
      run: |
        ls
        cd server/auth_service/test/
        . ../venv/bin/activate
        pip install pytest
        pytest --maxfail=1 --disable-warnings -q

    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: log
        path: server/log
