name: TEST

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:16
        env:
          POSTGRES_USER: homecloudauthsevice
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: homecloud
        volumes:
          - db_data:/var/lib/postgresql/data
        options: "--health-cmd \"pg_isready -U homecloudauthsevice\" --health-interval 10s --health-timeout 5s --health-retries 5"
        ports:
          - 5432:5432

      rabbitmq:
        image: rabbitmq:management
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        options: "--health-cmd \"rabbitmq-diagnostics ping\" --health-interval 10s --health-timeout 5s --health-retries 5"
        ports:
          - 5672:5672
          - 15672:15672

      log_service:
        image: daniilselin/homecloud:log_service
        options: "--health-cmd \"curl -f http://localhost:5672\" --health-interval 10s --health-timeout 5s --health-retries 5"
        volumes:
          - ./server/log/request:/request
          - ./server/log/error:/error
          - ./server/log/gRPC:/gRPC

      auth_service:
        image: daniilselin/homecloud:auth_service
        ports:
          - 5000:5000
        env:
          DATABASE_URL: postgresql+psycopg2://homecloudauthsevice:123@db:5432/homecloud
        options: "--health-cmd \"curl -f http://localhost:5000\" --health-interval 10s --health-timeout 5s --health-retries 5"
        volumes:
          - ./server/database_service:/server/database_service
          - ./server/.env:/server/.env
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Create symbolic link for server module
      run: |
        ln -s $GITHUB_WORKSPACE/server /home/runner/work/HomeCloud/HomeCloud/server/auth_service/
        echo "Symbolic link created for 'server'"

    - name: Run tests
      run: |
        . venv/bin/activate
        pip install pytest
        cd server/auth_service/test/
        pytest --maxfail=1 --disable-warnings -q

    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: log
        path: server/log
