name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PostgreSQL database
        run: |
          # Создаем бд и пользователя
          psql -h localhost -U postgres -c "CREATE DATABASE homecloud;"
          psql -h localhost -U postgres -d homecloud -c "CREATE USER homeclouduser WITH ENCRYPTED PASSWORD 'password';"
          psql -h localhost -U postgres -d homecloud -c "GRANT ALL PRIVILEGES ON DATABASE homecloud TO homeclouduser;"

      - name: Install dependencies
        run: |
          cd server/auth_service/test/
          pip install pytest

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Upload logs as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: log
          path: server/log
