name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Wait for PostgreSQL to be ready
        run: |
          sleep 10
          until psql -h localhost -U postgres -c "\q"; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Set up PostgreSQL database
        run: |
          export PGPASSWORD=postgres
          psql -h localhost -U postgres -c "CREATE DATABASE homecloud;"
          psql -h localhost -U postgres -d homecloud -c "CREATE USER homecloudauthsevice WITH ENCRYPTED PASSWORD '123';"
          psql -h localhost -U postgres -d homecloud -c "GRANT ALL PRIVILEGES ON DATABASE homecloud TO homecloudauthsevice;"

      - name: Verify PostgreSQL setup
        run: |
          export PGPASSWORD=postgres
          # Проверяем, существует ли база данных homecloud
          psql -h localhost -U postgres -c "SELECT 1 FROM pg_database WHERE datname='homecloud';" || { echo "Database homecloud does not exist."; exit 1; }
          # Проверяем, существует ли пользователь homecloudauthsevice
          psql -h localhost -U postgres -c "SELECT 1 FROM pg_roles WHERE rolname='homecloudauthsevice';" || { echo "User homecloudauthsevice does not exist."; exit 1; }
          echo "Database and user exisыt."

      - name: Check database connection
        run: |
          export PGPASSWORD=123
          psql -h localhost -U homecloudauthsevice -d homecloud -c "\q" || exit 1

      - name: Stop local PostgreSQL
        run: |
          sudo systemctl stop postgresql || echo "PostgreSQL is not running"

      - name: Restart Docker Daemon
        run: |
          sudo systemctl restart docker

      - name: Build and start services
        run: |
          cd server
          docker-compose -f docker-compose.yml up -d --build

      - name: Show Flask container logs
        run: docker logs server-auth_service-1

      - name: Run tests
        run: |
          cd server/auth_service/test/
          pip install pytest
          pytest --maxfail=1 --disable-warnings -q

      - name: Upload logs as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: log
          path: server/log
