name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: homecloudauthsevice
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: homecloud
        ports:
          - 5432:5432
        volumes:
          - db_data:/var/lib/postgresql/data

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        cd server
        docker build -t auth_service -f auth_service/Dockerfile .

    - name: Run Docker container
      run: docker run -d -p 5000:5000 auth_service

    - name: Check if auth_service is running
      run: |
        echo "Waiting for auth_service to start..."
        sleep 10 # Даем время на запуск
        response=$(curl --write-out "%{http_code}\n" --silent --output /dev/null http://localhost:5000/health) # Замените на правильный путь для проверки
        if [ "$response" -ne 200 ]; then
          echo "auth_service is not running properly. HTTP status code: $response"
          exit 1
        else
          echo "auth_service is running and reachable!"
        fi

    - name: Run tests
      run: |
        ls
        cd server/auth_service/test/
        pip install pytest
        pytest --maxfail=1 --disable-warnings -q

    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: log
        path: server/log
