name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: homecloudauthsevice
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: homecloud
        ports:
          - 5432:5432
        volumes:
          - db_data:/var/lib/postgresql/data

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r server/auth_service/requirements.txt

    - name: Install RabbitMQ
      run: |
        sudo apt-get update
        sudo apt-get install -y rabbitmq-server
        sudo systemctl start rabbitmq-server
        sudo systemctl enable rabbitmq-server

    - name: Create symbolic link for server module
      run: |
        ln -s $GITHUB_WORKSPACE/server /home/runner/work/HomeCloud/HomeCloud/server/auth_service/
        echo "Symbolic link created for 'server'"

    - name: Wait for RabbitMQ to be ready
      run: |
        echo "Waiting for RabbitMQ to be ready..."
        for i in {1..30}; do
          if nc -z rabbitmq 5672; then
            echo "RabbitMQ is ready!"
            break
          fi
          echo "Waiting for RabbitMQ..."
          sleep 1
        done

    - name: Start log_service
      run: |
        . venv/bin/activate
        pip install pika
        ls ./server/log
        python3 ./server/log/LOG_service.py &  # Запуск сервиса в фоновом режиме
        sleep 10 # Даем время на запуск

    - name: Start auth_service
      run: |
        . venv/bin/activate
        ls ./server/auth_service
        python3 ./server/auth_service/auth_service.py &  # Запуск сервиса в фоновом режиме
        sleep 10 # Даем время на запуск

    - name: Run tests
      run: |
        . venv/bin/activate
        pip install pytest
        cd server/auth_service/test/
        pytest --maxfail=1 --disable-warnings -q

    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: log
        path: server/log
